# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{yogo-support}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Heimbuch"]
  s.date = %q{2010-10-06}
  s.description = %q{Supporting extensions for yogo libraries.}
  s.email = %q{rheimbuch@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/step_definitions/yogo-support_steps.rb",
    "features/support/env.rb",
    "features/yogo-support.feature",
    "lib/yogo/support/extension_module.rb",
    "lib/yogo/support/object/apply.rb",
    "lib/yogo/support/proc.rb",
    "lib/yogo/support/proc/call.rb",
    "lib/yogo/support/proc/compose.rb",
    "lib/yogo/support/proc/partial.rb",
    "spec/extension_module_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/yogo/yogo-support}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Supporting extensions for yogo libraries.}
  s.description = %q{Supporting code for the Yogo Data Management Framework components.}
  s.test_files = [
    "spec/extension_module_spec.rb",
    "spec/spec_helper.rb"
  ]
  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3
    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      #
    else
      #
    end
  else
    #
  end
end

